# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(802, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 781, 561))
        self.stackedWidget.setObjectName("stackedWidget")
        self.First = QtWidgets.QWidget()
        self.First.setObjectName("First")
        self.textBrowser = QtWidgets.QTextBrowser(self.First)
        self.textBrowser.setGeometry(QtCore.QRect(0, 20, 781, 201))
        self.textBrowser.setObjectName("textBrowser")
        self.label = QtWidgets.QLabel(self.First)
        self.label.setGeometry(QtCore.QRect(-40, -60, 1181, 861))
        self.label.setObjectName("label")
        self.learn_btn = QtWidgets.QPushButton(self.First)
        self.learn_btn.setGeometry(QtCore.QRect(20, 310, 241, 191))
        self.learn_btn.setMouseTracking(False)
        self.learn_btn.setObjectName("learn_btn")
        self.test_btn = QtWidgets.QPushButton(self.First)
        self.test_btn.setGeometry(QtCore.QRect(520, 310, 241, 191))
        self.test_btn.setObjectName("test_btn")
        self.label.raise_()
        self.learn_btn.raise_()
        self.test_btn.raise_()
        self.textBrowser.raise_()
        self.stackedWidget.addWidget(self.First)
        self.Learning_meet = QtWidgets.QWidget()
        self.Learning_meet.setObjectName("Learning_meet")
        self.textBrowser_learn = QtWidgets.QTextBrowser(self.Learning_meet)
        self.textBrowser_learn.setGeometry(QtCore.QRect(10, 30, 751, 201))
        self.textBrowser_learn.setObjectName("textBrowser_learn")
        self.learning_back_btn = QtWidgets.QPushButton(self.Learning_meet)
        self.learning_back_btn.setGeometry(QtCore.QRect(590, 500, 181, 31))
        self.learning_back_btn.setObjectName("learning_back_btn")
        self.learning_start_btn = QtWidgets.QPushButton(self.Learning_meet)
        self.learning_start_btn.setGeometry(QtCore.QRect(380, 260, 381, 171))
        self.learning_start_btn.setObjectName("learning_start_btn")
        self.label_3 = QtWidgets.QLabel(self.Learning_meet)
        self.label_3.setGeometry(QtCore.QRect(20, 320, 181, 31))
        self.label_3.setObjectName("label_3")
        self.comboBox = QtWidgets.QComboBox(self.Learning_meet)
        self.comboBox.setGeometry(QtCore.QRect(210, 320, 161, 31))
        self.comboBox.setObjectName("comboBox")
        self.stackedWidget.addWidget(self.Learning_meet)
        self.Learning = QtWidgets.QWidget()
        self.Learning.setObjectName("Learning")
        self.l_back_btn = QtWidgets.QPushButton(self.Learning)
        self.l_back_btn.setGeometry(QtCore.QRect(622, 510, 131, 28))
        self.l_back_btn.setObjectName("l_back_btn")
        self.lable_learn = QtWidgets.QLabel(self.Learning)
        self.lable_learn.setGeometry(QtCore.QRect(340, 90, 401, 391))
        self.lable_learn.setText("")
        self.lable_learn.setObjectName("lable_learn")
        self.comboBox_learn = QtWidgets.QComboBox(self.Learning)
        self.comboBox_learn.setGeometry(QtCore.QRect(10, 30, 291, 21))
        self.comboBox_learn.setObjectName("comboBox_learn")
        self.pushButton_learn = QtWidgets.QPushButton(self.Learning)
        self.pushButton_learn.setGeometry(QtCore.QRect(320, 30, 121, 21))
        self.pushButton_learn.setObjectName("pushButton_learn")
        self.info_learn = QtWidgets.QTextBrowser(self.Learning)
        self.info_learn.setGeometry(QtCore.QRect(20, 100, 281, 281))
        self.info_learn.setObjectName("info_learn")
        self.stackedWidget.addWidget(self.Learning)
        self.Testing_meet = QtWidgets.QWidget()
        self.Testing_meet.setObjectName("Testing_meet")
        self.textBrowser_3 = QtWidgets.QTextBrowser(self.Testing_meet)
        self.textBrowser_3.setGeometry(QtCore.QRect(0, 40, 761, 231))
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.testing_back_btn = QtWidgets.QPushButton(self.Testing_meet)
        self.testing_back_btn.setGeometry(QtCore.QRect(620, 510, 141, 31))
        self.testing_back_btn.setObjectName("testing_back_btn")
        self.testing_start_btn = QtWidgets.QPushButton(self.Testing_meet)
        self.testing_start_btn.setGeometry(QtCore.QRect(400, 300, 361, 171))
        self.testing_start_btn.setObjectName("testing_start_btn")
        self.get_name = QtWidgets.QLineEdit(self.Testing_meet)
        self.get_name.setGeometry(QtCore.QRect(10, 340, 231, 20))
        self.get_name.setObjectName("get_name")
        self.label_5 = QtWidgets.QLabel(self.Testing_meet)
        self.label_5.setGeometry(QtCore.QRect(10, 300, 161, 41))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.Testing_meet)
        self.label_6.setGeometry(QtCore.QRect(10, 380, 111, 16))
        self.label_6.setObjectName("label_6")
        self.comboBox_theme = QtWidgets.QComboBox(self.Testing_meet)
        self.comboBox_theme.setGeometry(QtCore.QRect(10, 410, 161, 22))
        self.comboBox_theme.setObjectName("comboBox_theme")
        self.stackedWidget.addWidget(self.Testing_meet)
        self.Testing = QtWidgets.QWidget()
        self.Testing.setObjectName("Testing")
        self.label_testing = QtWidgets.QLabel(self.Testing)
        self.label_testing.setGeometry(QtCore.QRect(20, 20, 441, 31))
        self.label_testing.setObjectName("label_testing")
        self.textBrowser_task = QtWidgets.QTextBrowser(self.Testing)
        self.textBrowser_task.setGeometry(QtCore.QRect(30, 60, 731, 91))
        self.textBrowser_task.setObjectName("textBrowser_task")
        self.lineEdit = QtWidgets.QLineEdit(self.Testing)
        self.lineEdit.setGeometry(QtCore.QRect(120, 230, 431, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.label_2 = QtWidgets.QLabel(self.Testing)
        self.label_2.setGeometry(QtCore.QRect(40, 220, 121, 41))
        self.label_2.setObjectName("label_2")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.Testing)
        self.textBrowser_2.setGeometry(QtCore.QRect(50, 270, 401, 281))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.testing_btn = QtWidgets.QPushButton(self.Testing)
        self.testing_btn.setGeometry(QtCore.QRect(580, 230, 93, 28))
        self.testing_btn.setObjectName("testing_btn")
        self.get_result_btn = QtWidgets.QPushButton(self.Testing)
        self.get_result_btn.setEnabled(True)
        self.get_result_btn.setGeometry(QtCore.QRect(580, 280, 131, 28))
        self.get_result_btn.setFlat(False)
        self.get_result_btn.setObjectName("get_result_btn")
        self.stackedWidget.addWidget(self.Testing)
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.label_4 = QtWidgets.QLabel(self.page)
        self.label_4.setGeometry(QtCore.QRect(10, 30, 41, 41))
        self.label_4.setObjectName("label_4")
        self.label_7 = QtWidgets.QLabel(self.page)
        self.label_7.setGeometry(QtCore.QRect(10, 100, 55, 16))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.page)
        self.label_8.setGeometry(QtCore.QRect(10, 150, 71, 16))
        self.label_8.setObjectName("label_8")
        self.textBrowser_name = QtWidgets.QTextBrowser(self.page)
        self.textBrowser_name.setGeometry(QtCore.QRect(90, 40, 256, 31))
        self.textBrowser_name.setObjectName("textBrowser_name")
        self.textBrowser_theme = QtWidgets.QTextBrowser(self.page)
        self.textBrowser_theme.setGeometry(QtCore.QRect(90, 90, 256, 31))
        self.textBrowser_theme.setObjectName("textBrowser_theme")
        self.textBrowser_result = QtWidgets.QTextBrowser(self.page)
        self.textBrowser_result.setGeometry(QtCore.QRect(90, 140, 256, 31))
        self.textBrowser_result.setObjectName("textBrowser_result")
        self.tableWidget = QtWidgets.QTableWidget(self.page)
        self.tableWidget.setGeometry(QtCore.QRect(30, 230, 481, 301))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.label_9 = QtWidgets.QLabel(self.page)
        self.label_9.setGeometry(QtCore.QRect(30, 200, 141, 16))
        self.label_9.setObjectName("label_9")
        self.result_back_btn = QtWidgets.QPushButton(self.page)
        self.result_back_btn.setGeometry(QtCore.QRect(620, 510, 141, 28))
        self.result_back_btn.setObjectName("result_back_btn")
        self.differense = QtWidgets.QTextBrowser(self.page)
        self.differense.setGeometry(QtCore.QRect(370, 60, 421, 151))
        self.differense.setObjectName("differense")
        self.label_10 = QtWidgets.QLabel(self.page)
        self.label_10.setGeometry(QtCore.QRect(440, 30, 281, 16))
        self.label_10.setObjectName("label_10")
        self.stackedWidget.addWidget(self.page)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 802, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt;\">Приветствуем Вас в </span><span style=\" font-size:18pt; font-weight:600;\">GeomHelper.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt;\">Данное приложение создано для обучения школьников планиметрии. Выберите обучение или тестирование</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:18pt;\"><br /></p></body></html>"))
        self.label.setText(_translate("MainWindow", "TextLabel"))
        self.learn_btn.setText(_translate("MainWindow", "Учить!"))
        self.test_btn.setText(_translate("MainWindow", "Тестироваться!"))
        self.textBrowser_learn.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:36pt; font-weight:600;\">Приветствую  в обучении!</span></p></body></html>"))
        self.learning_back_btn.setText(_translate("MainWindow", "НАЗАД НА ГЛАВНУЮ"))
        self.learning_start_btn.setText(_translate("MainWindow", "НАЧАТЬ ОБУЧЕНИЕ"))
        self.label_3.setText(_translate("MainWindow", "Выберите фигуру для изучения"))
        self.l_back_btn.setText(_translate("MainWindow", "НАЗАД НА ГЛАВНУЮ"))
        self.pushButton_learn.setText(_translate("MainWindow", "Показать формулу"))
        self.info_learn.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:6.6pt;\"><br /></p></body></html>"))
        self.textBrowser_3.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:36pt; font-weight:600;\">Приветствую Вас в Тестировании</span></p></body></html>"))
        self.testing_back_btn.setText(_translate("MainWindow", "НАЗАД НА ГЛАВНУЮ"))
        self.testing_start_btn.setText(_translate("MainWindow", "НАЧАТЬ ТЕСТИРОВАНИЕ"))
        self.label_5.setText(_translate("MainWindow", "Ведиьте Ваше Имя и Фамилию"))
        self.label_6.setText(_translate("MainWindow", "Выберите Тему"))
        self.label_testing.setText(_translate("MainWindow", "Тест по теме: "))
        self.label_2.setText(_translate("MainWindow", "Ваш ответ:"))
        self.textBrowser_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Ответ вводите в формате S = a * b * 0.5.<br />Формулы писать так, как они были написаны в обучении</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Деление на 2 обозначьте, как умножение на 0.5</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Радиус описанной окружности R</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Радиус вписанной окружности r</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Площадь S</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Прериметр P</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Полупериметр p</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Стороны фигуры a, b, c</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Диагонали d1, d2</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Корень квадратный sqrt()</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Возведение в квадрат ^2</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Число Пи Pi</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Угол альфа обозначтьте за a</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">a, b - катеты прямоугольного треугольника</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">c - гипотенуза</p></body></html>"))
        self.testing_btn.setText(_translate("MainWindow", "Дать ответ"))
        self.get_result_btn.setText(_translate("MainWindow", "Получить результат"))
        self.label_4.setText(_translate("MainWindow", "Имя:"))
        self.label_7.setText(_translate("MainWindow", "Тема:"))
        self.label_8.setText(_translate("MainWindow", "Результат"))
        self.label_9.setText(_translate("MainWindow", "Таблица результатов"))
        self.result_back_btn.setText(_translate("MainWindow", "НАЗАД НА ГЛАВНУЮ"))
        self.label_10.setText(_translate("MainWindow", "Ошибки. Ваш ответ и веный ответ"))
